### ISSUE TITLE
MalathiYalamarthi

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#30]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by MalathiYalamarthi** [comment]
I'm Malathi Yalamarthi, a computer science student with a passion for [Your Interests]. I'm excited to join this project and contribute my skills to make a meaningful impact.

What drew me to this project is its innovative mission to democratize access to education through open source software. Additionally, the project's robust technology stack and the vibrant community around it are also major attractions.

I've chosen to work on issue #30 because it aligns perfectly with my expertise in backend development, and I'm eager to delve deeper into optimizing database queries for performance.

My goal for this issue is to enhance the backend performance by optimizing critical database queries. I'm looking forward to collaborating with all of you to accomplish this.

Looking forward to diving in and contributing! If you have any insights or guidance on this issue, or if there are specific aspects you think I should focus on, I'd love to hear from you.

**Comment by MalathiYalamarthi** [comment]
Hello @caiton1 

I hope you're doing well. I wanted to reach out to you regarding issue #30 that I've recently assigned to myself. As I delve into improving the accessibility features of the user interface, I believe your expertise could provide valuable insights into best practices or specific challenges related to this task.

Your contributions to the project have been impressive, and I would greatly appreciate any guidance or advice you can offer to help me navigate this issue effectively. Your insights could play a crucial role in achieving our goal of enhancing user experience through accessibility improvements.

Thank you in advance for considering my request. I look forward to collaborating with you and learning from your expertise.

**Comment by MalathiYalamarthi** [comment]
Hello @caiton1 

I hope you're doing well. I wanted to reach out to you regarding issue https://github.com/NAU-OSS/jabref/issues/30 that I've recently assigned to myself. As I delve into improving the accessibility features of the user interface, I believe your expertise could provide valuable insights into best practices or specific challenges related to this task.

Your contributions to the project have been impressive, and I would greatly appreciate any guidance or advice you can offer to help me navigate this issue effectively. Your insights could play a crucial role in achieving our goal of enhancing user experience through accessibility improvements.

Thank you in advance for considering my request. I look forward to collaborating with you and learning from your expertise.
