### ISSUE TITLE
saiTharunDusa

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#35]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by saiTharunDusa** [comment]
I'm really excited to be a part of this project and help make it easier for everyone to get involved. My name is Sai Tharun Dusa, and I love the idea of making open-source projects more friendly and understandable for new people. The idea to move and simplify the contributing section in the Readme file is exactly what I was hoping for. I think that if we organize the information clearly, it will be much simpler for newbies to figure out how they can help with the project. I can't wait to start working on this and team up with all of you to make these changes. If anyone has any thoughts or ideas on how we can tackle this task, please share them with me.
Excited to work together!

**Comment by saiTharunDusa** [comment]
Hi @caiton1,
I wanted to reach out to you because I really value your expertise and insights. Your contributions to the project have been amazing, and I think your perspective could really help us improve the accessibility of the project's Readme file. I was wondering if you could share your thoughts on the idea of moving and simplifying the Contributing section of the Readme file. Your guidance would be super helpful as we try to make the project more friendly for newbies.
Thank you so much for considering my request and for all the awesome work you've been doing for the project!

Best Regards,
Sai Tharun Dusa
