### ISSUE TITLE
gurramtejaswini

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#71]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by gurramtejaswini** [comment]
Hello, 
I am Tejaswini. I am very happy to contribute to open source software it was really fun. I have noticed that the issue which was assigned to me doesn't have a proper READme file which is very important for the contribution of any work because rhe Readme file consists about the indepth knowledge about work/project that plays very crucial role to get the appropriate results.
So, I would like to work on this issue.

**Comment by gurramtejaswini** [comment]
Hello @caiton1 I would like to ask you for insights regarding an issue that is mentioned, which will be very heplful for my contributions to open source software. I would be thankful for your help.

**Comment by gurramtejaswini** [comment]
Closing tihs issue as I have made changes and commited the pull request.
