### ISSUE TITLE
KSVeerendernath

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#74]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by KSVeerendernath** [comment]
Hi, I'm Veerendernath. I love coding and I've worked with technologies like Java and Spring Boot. 

I wanted to improve this project's README file because it's essential. A good README helps everyone understand a project easily. It should include things like:

 What the project does:  A description of its purpose.
 Who made it: My information.
 Any problems: If there are any bugs or issues.
 How to run it: Instructions on how to get the project working.
 How to test it: Instructions on how to run tests (if there are any).

The current README needs to be shorter and simpler. I want to make it easier to understand and look more professional.

**Comment by KSVeerendernath** [comment]
Hi @caiton1,  Hope you’re doing great! First of all, I would like to appreciate your efforts and contributions to this community kudos! I would love to get your insights and advice on improving the README file. Your efforts will be greatly appreciated.

**Comment by KSVeerendernath** [comment]
Hi All, Closing this issue as it has been fixed, @caiton1 I created PR - #96 and it is waiting for your review. Thanks.
