### ISSUE TITLE
shethshlok

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#87]
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by shethshlok** [comment]
Hello Developers, My name is Shlok Sheth, I am a full stack developer completing my masters in Computer Science at Northern Arizona University, in Flagstaff. I am in enrolled in CS 599 - Open Source Development class. This is is my first issue in this repository and my goal is to resolve and redefine the README file so that user and new visitors have a clear idea about the project especially the contributing section.

**Comment by shethshlok** [comment]
Hey @caiton1, I would appreciate your advise, given your contribution to this project and expertise, could you recommend me any specific changes I should make to the README file. Here is what I think:
1) Shift the Contributing section to the top.
2) Add more images or flow chart to the read me to explain it to a new visitor
3) Add installation instruction for different operating systems.

**Comment by shethshlok** [comment]
I have resolved the issue and filed a pull request #109
